# Generated by Django 3.2.5 on 2021-08-01 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, verbose_name='title')),
                ('type', models.CharField(default='contact', max_length=20, verbose_name='type')),
                ('recipient', models.EmailField(max_length=254, verbose_name='recipient email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission form',
                'verbose_name_plural': 'Submission forms',
            },
        ),
    ]
